package com.example.wlwlxgg.mymusic.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.wlwlxgg.mymusic.entity.MusicDownloadEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MUSIC_DOWNLOAD_ENTITY".
*/
public class MusicDownloadEntityDao extends AbstractDao<MusicDownloadEntity, String> {

    public static final String TABLENAME = "MUSIC_DOWNLOAD_ENTITY";

    /**
     * Properties of entity MusicDownloadEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property SongId = new Property(0, String.class, "songId", true, "SONG_ID");
        public final static Property Time = new Property(1, String.class, "time", false, "TIME");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Album = new Property(4, String.class, "album", false, "ALBUM");
        public final static Property LrcLink = new Property(5, String.class, "lrcLink", false, "LRC_LINK");
        public final static Property FileLink = new Property(6, String.class, "fileLink", false, "FILE_LINK");
        public final static Property ImageSmall = new Property(7, String.class, "imageSmall", false, "IMAGE_SMALL");
        public final static Property ImageMid = new Property(8, String.class, "imageMid", false, "IMAGE_MID");
        public final static Property ImageBig = new Property(9, String.class, "imageBig", false, "IMAGE_BIG");
        public final static Property SavePath = new Property(10, String.class, "savePath", false, "SAVE_PATH");
        public final static Property BaseUrl = new Property(11, String.class, "baseUrl", false, "BASE_URL");
        public final static Property ContentLength = new Property(12, long.class, "contentLength", false, "CONTENT_LENGTH");
        public final static Property ReadLength = new Property(13, long.class, "readLength", false, "READ_LENGTH");
        public final static Property Status = new Property(14, int.class, "status", false, "STATUS");
    }


    public MusicDownloadEntityDao(DaoConfig config) {
        super(config);
    }
    
    public MusicDownloadEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MUSIC_DOWNLOAD_ENTITY\" (" + //
                "\"SONG_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: songId
                "\"TIME\" TEXT," + // 1: time
                "\"TITLE\" TEXT," + // 2: title
                "\"AUTHOR\" TEXT," + // 3: author
                "\"ALBUM\" TEXT," + // 4: album
                "\"LRC_LINK\" TEXT," + // 5: lrcLink
                "\"FILE_LINK\" TEXT," + // 6: fileLink
                "\"IMAGE_SMALL\" TEXT," + // 7: imageSmall
                "\"IMAGE_MID\" TEXT," + // 8: imageMid
                "\"IMAGE_BIG\" TEXT," + // 9: imageBig
                "\"SAVE_PATH\" TEXT," + // 10: savePath
                "\"BASE_URL\" TEXT," + // 11: baseUrl
                "\"CONTENT_LENGTH\" INTEGER NOT NULL ," + // 12: contentLength
                "\"READ_LENGTH\" INTEGER NOT NULL ," + // 13: readLength
                "\"STATUS\" INTEGER NOT NULL );"); // 14: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MUSIC_DOWNLOAD_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MusicDownloadEntity entity) {
        stmt.clearBindings();
 
        String songId = entity.getSongId();
        if (songId != null) {
            stmt.bindString(1, songId);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String album = entity.getAlbum();
        if (album != null) {
            stmt.bindString(5, album);
        }
 
        String lrcLink = entity.getLrcLink();
        if (lrcLink != null) {
            stmt.bindString(6, lrcLink);
        }
 
        String fileLink = entity.getFileLink();
        if (fileLink != null) {
            stmt.bindString(7, fileLink);
        }
 
        String imageSmall = entity.getImageSmall();
        if (imageSmall != null) {
            stmt.bindString(8, imageSmall);
        }
 
        String imageMid = entity.getImageMid();
        if (imageMid != null) {
            stmt.bindString(9, imageMid);
        }
 
        String imageBig = entity.getImageBig();
        if (imageBig != null) {
            stmt.bindString(10, imageBig);
        }
 
        String savePath = entity.getSavePath();
        if (savePath != null) {
            stmt.bindString(11, savePath);
        }
 
        String baseUrl = entity.getBaseUrl();
        if (baseUrl != null) {
            stmt.bindString(12, baseUrl);
        }
        stmt.bindLong(13, entity.getContentLength());
        stmt.bindLong(14, entity.getReadLength());
        stmt.bindLong(15, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MusicDownloadEntity entity) {
        stmt.clearBindings();
 
        String songId = entity.getSongId();
        if (songId != null) {
            stmt.bindString(1, songId);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(2, time);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(4, author);
        }
 
        String album = entity.getAlbum();
        if (album != null) {
            stmt.bindString(5, album);
        }
 
        String lrcLink = entity.getLrcLink();
        if (lrcLink != null) {
            stmt.bindString(6, lrcLink);
        }
 
        String fileLink = entity.getFileLink();
        if (fileLink != null) {
            stmt.bindString(7, fileLink);
        }
 
        String imageSmall = entity.getImageSmall();
        if (imageSmall != null) {
            stmt.bindString(8, imageSmall);
        }
 
        String imageMid = entity.getImageMid();
        if (imageMid != null) {
            stmt.bindString(9, imageMid);
        }
 
        String imageBig = entity.getImageBig();
        if (imageBig != null) {
            stmt.bindString(10, imageBig);
        }
 
        String savePath = entity.getSavePath();
        if (savePath != null) {
            stmt.bindString(11, savePath);
        }
 
        String baseUrl = entity.getBaseUrl();
        if (baseUrl != null) {
            stmt.bindString(12, baseUrl);
        }
        stmt.bindLong(13, entity.getContentLength());
        stmt.bindLong(14, entity.getReadLength());
        stmt.bindLong(15, entity.getStatus());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MusicDownloadEntity readEntity(Cursor cursor, int offset) {
        MusicDownloadEntity entity = new MusicDownloadEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // songId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // time
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // author
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // album
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // lrcLink
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // fileLink
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // imageSmall
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // imageMid
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // imageBig
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // savePath
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // baseUrl
            cursor.getLong(offset + 12), // contentLength
            cursor.getLong(offset + 13), // readLength
            cursor.getInt(offset + 14) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MusicDownloadEntity entity, int offset) {
        entity.setSongId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthor(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAlbum(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLrcLink(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFileLink(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImageSmall(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setImageMid(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setImageBig(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSavePath(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setBaseUrl(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setContentLength(cursor.getLong(offset + 12));
        entity.setReadLength(cursor.getLong(offset + 13));
        entity.setStatus(cursor.getInt(offset + 14));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MusicDownloadEntity entity, long rowId) {
        return entity.getSongId();
    }
    
    @Override
    public String getKey(MusicDownloadEntity entity) {
        if(entity != null) {
            return entity.getSongId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MusicDownloadEntity entity) {
        return entity.getSongId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
